/**:
  ros__parameters:
    camera_info_url: package://driver_bringup/config/camera_info.yaml
    video_path: package://resource/video/traffic_sign1.mp4
    max_fps: 60
    start_frame: 0
    frame_id: "camera_optical_frame"
    keep_looping: true              #是否循环播放
